### PR TITLE
Add support for metad & mond

### PR DESCRIPTION
**Pull request by ramereth**
This adds support for building the metad and mond daemons which require several
more Haskell dependencies. This includes versions of snap-server which will
build on EPEL7.

In addition, I fixed a few typos and a missing m4 package build dependency for
the ganeti spec file.

Signed-off-by: Lance Albertson <lance@osuosl.org>

### CODE REVIEW

**Comment by jfut** [comment]
I'll check it out later. Many thanks!

**Comment by ramereth** [comment]
@jfut I see you document much of the dependencies in a doc file. Would you like me to update that?

**Comment by jfut** [comment]
It would be very helpful if possible.

**Comment by jfut** [comment]
metad & mond worked fine!
Ganeti-2.16.1-2 will be released within a few days.

**Comment by jfut** [comment]
I have released Ganeti 2.16.1-2 RPM. Thanks!
https://github.com/jfut/ganeti-rpm/releases/tag/v2.16.1-2
https://jfut.integ.jp/linux/ganeti/

**Pull request merged**
